package fr.eseo.ldcr.webservices.visite;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.18 2016-03-17T17:48:35.822+01:00 Generated source
 * version: 2.7.18
 * 
 */
@WebServiceClient(name = "GestionService",
    wsdlLocation = "http://192.168.4.197:8080/VisitesServeur/services/GestionPort?wsdl",
    targetNamespace = "http://visite.ldcr.eseo.fr/")
public class GestionService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://visite.ldcr.eseo.fr/", "GestionService");
  public final static QName GestionPort = new QName("http://visite.ldcr.eseo.fr/", "GestionPort");
  static {
    URL url = null;
    try {
      url = new URL("http://192.168.4.197:8080/VisitesServeur/services/GestionPort?wsdl");
    } catch (final MalformedURLException e) {
      java.util.logging.Logger.getLogger(GestionService.class.getName()).log(
          java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://192.168.4.197:8080/VisitesServeur/services/GestionPort?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public GestionService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public GestionService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public GestionService() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public GestionService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public GestionService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public GestionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns VisitesServeur
   */
  @WebEndpoint(name = "GestionPort")
  public VisitesServeur getGestionPort() {
    return super.getPort(GestionPort, VisitesServeur.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns VisitesServeur
   */
  @WebEndpoint(name = "GestionPort")
  public VisitesServeur getGestionPort(WebServiceFeature... features) {
    return super.getPort(GestionPort, VisitesServeur.class, features);
  }

}
