package fr.eseo.ldcr.webservices.visite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18 2016-03-17T17:48:35.813+01:00 Generated source
 * version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://visite.ldcr.eseo.fr/", name = "VisitesServeur")
@XmlSeeAlso({ObjectFactory.class})
public interface VisitesServeur {

  @WebResult(name = "return", targetNamespace = "")
  @RequestWrapper(localName = "trouverVisite", targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.TrouverVisite")
  @WebMethod
  @ResponseWrapper(localName = "trouverVisiteResponse",
      targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.TrouverVisiteResponse")
  public java.util.List<fr.eseo.ldcr.webservices.visite.Visite> trouverVisite(
      @WebParam(name = "arg0", targetNamespace = "") fr.eseo.ldcr.webservices.visite.Visite arg0,
      @WebParam(name = "arg1", targetNamespace = "") float arg1,
      @WebParam(name = "arg2", targetNamespace = "") javax.xml.datatype.XMLGregorianCalendar arg2);

  @WebResult(name = "return", targetNamespace = "")
  @RequestWrapper(localName = "payerVisite", targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.PayerVisite")
  @WebMethod
  @ResponseWrapper(localName = "payerVisiteResponse",
      targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.PayerVisiteResponse")
  public boolean payerVisite(@WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0);

  @WebResult(name = "return", targetNamespace = "")
  @RequestWrapper(localName = "annulerVisite", targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.AnnulerVisite")
  @WebMethod
  @ResponseWrapper(localName = "annulerVisiteResponse",
      targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.AnnulerVisiteResponse")
  public boolean annulerVisite(
      @WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0);

  @WebResult(name = "return", targetNamespace = "")
  @RequestWrapper(localName = "reserverVisite", targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.ReserverVisite")
  @WebMethod
  @ResponseWrapper(localName = "reserverVisiteResponse",
      targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.ReserverVisiteResponse")
  public java.lang.String reserverVisite(@WebParam(name = "arg0",
      targetNamespace = "") fr.eseo.ldcr.webservices.visite.ReservationVisite arg0);

  @WebResult(name = "return", targetNamespace = "")
  @RequestWrapper(localName = "trouverReservation", targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.TrouverReservation")
  @WebMethod
  @ResponseWrapper(localName = "trouverReservationResponse",
      targetNamespace = "http://visite.ldcr.eseo.fr/",
      className = "fr.eseo.ldcr.webservices.visite.TrouverReservationResponse")
  public java.util.List<fr.eseo.ldcr.webservices.visite.ReservationVisite> trouverReservation(
      @WebParam(name = "arg0",
          targetNamespace = "") fr.eseo.ldcr.webservices.visite.ReservationVisite arg0);
}
