
/**
 * Please modify this class to meet your needs This class is not complete
 */

package javaee.spectacle.webservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.18 2016-03-16T20:46:16.687+01:00 Generated source
 * version: 2.7.18
 * 
 */

@javax.jws.WebService(serviceName = "GestionSpectaclesService", portName = "GestionSpectaclesPort",
    targetNamespace = "http://webservices.spectacle.javaee/",
    wsdlLocation = "http://localhost:8080/GestionSpectacles/services/GestionSpectaclesPort?wsdl",
    endpointInterface = "javaee.spectacle.webservices.WSGestionSpectacles")

public class WSGestionSpectaclesImpl implements WSGestionSpectacles {

  private static final Logger LOG = Logger.getLogger(WSGestionSpectaclesImpl.class.getName());

  /*
   * (non-Javadoc)
   * 
   * @see
   * javaee.spectacle.webservices.WSGestionSpectacles#reserverSpectacle(javaee.spectacle.webservices
   * .Reservation arg0 )*
   */
  @Override
  public int reserverSpectacle(javaee.spectacle.webservices.Reservation arg0) {
    LOG.info("Executing operation reserverSpectacle");
    System.out.println(arg0);
    try {
      final int _return = -77078073;
      return _return;
    } catch (final java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see javaee.spectacle.webservices.WSGestionSpectacles#recupererReservation(int arg0 )*
   */
  @Override
  public java.util.List<javaee.spectacle.webservices.Reservation> recupererReservation(int arg0) {
    LOG.info("Executing operation recupererReservation");
    System.out.println(arg0);
    try {
      final java.util.List<javaee.spectacle.webservices.Reservation> _return =
          new java.util.ArrayList<javaee.spectacle.webservices.Reservation>();
      final javaee.spectacle.webservices.Reservation _returnVal1 =
          new javaee.spectacle.webservices.Reservation();
      _returnVal1.setIdClient(-1237033013);
      _returnVal1.setIdReservation(Integer.valueOf(498626121));
      _returnVal1.setIdSpectacle(Integer.valueOf(-1165158956));
      _returnVal1.setNombrePlaces(Integer.valueOf(-605740846));
      _returnVal1.setPaiement(Boolean.valueOf(false));
      _return.add(_returnVal1);
      return _return;
    } catch (final java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see javaee.spectacle.webservices.WSGestionSpectacles#payerSpectacle(int arg0 )*
   */
  @Override
  public boolean payerSpectacle(int arg0) {
    LOG.info("Executing operation payerSpectacle");
    System.out.println(arg0);
    try {
      final boolean _return = true;
      return _return;
    } catch (final java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see javaee.spectacle.webservices.WSGestionSpectacles#annulerSpectacle(int arg0 )*
   */
  @Override
  public boolean annulerSpectacle(int arg0) {
    LOG.info("Executing operation annulerSpectacle");
    System.out.println(arg0);
    try {
      final boolean _return = false;
      return _return;
    } catch (final java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see
   * javaee.spectacle.webservices.WSGestionSpectacles#trouverSpectacle(javaee.spectacle.webservices.
   * Spectacle arg0 )*
   */
  @Override
  public java.util.List<javaee.spectacle.webservices.Spectacle> trouverSpectacle(
      javaee.spectacle.webservices.Spectacle arg0) {
    LOG.info("Executing operation trouverSpectacle");
    System.out.println(arg0);
    try {
      final java.util.List<javaee.spectacle.webservices.Spectacle> _return =
          new java.util.ArrayList<javaee.spectacle.webservices.Spectacle>();
      final javaee.spectacle.webservices.Spectacle _returnVal1 =
          new javaee.spectacle.webservices.Spectacle();
      _returnVal1.setDate(Long.valueOf(-4726178941056340543l));
      _returnVal1.setId(Integer.valueOf(-741487529));
      _returnVal1.setPrix(Integer.valueOf(-1931755533));
      _returnVal1.setTitre("Titre1959443573");
      _returnVal1.setType("Type622058188");
      _returnVal1.setVille("Ville-113450485");
      _return.add(_returnVal1);
      return _return;
    } catch (final java.lang.Exception ex) {
      ex.printStackTrace();
      throw new RuntimeException(ex);
    }
  }

}
