
package javaee.spectacle.webservices;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.18 2016-03-16T20:46:16.619+01:00 Generated source
 * version: 2.7.18
 * 
 */
public final class WSGestionSpectacles_GestionSpectaclesPort_Client {

  private static final QName SERVICE_NAME =
      new QName("http://webservices.spectacle.javaee/", "GestionSpectaclesService");

  private WSGestionSpectacles_GestionSpectaclesPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = GestionSpectaclesService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      final File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (final MalformedURLException e) {
        e.printStackTrace();
      }
    }

    final GestionSpectaclesService ss = new GestionSpectaclesService(wsdlURL, SERVICE_NAME);
    final WSGestionSpectacles port = ss.getGestionSpectaclesPort();

    {
      System.out.println("Invoking reserverSpectacle...");
      final javaee.spectacle.webservices.Reservation _reserverSpectacle_arg0 =
          new javaee.spectacle.webservices.Reservation();
      _reserverSpectacle_arg0.setIdClient(-1431271075);
      _reserverSpectacle_arg0.setIdReservation(Integer.valueOf(14914427));
      _reserverSpectacle_arg0.setIdSpectacle(Integer.valueOf(-333268256));
      _reserverSpectacle_arg0.setNombrePlaces(Integer.valueOf(-27069668));
      _reserverSpectacle_arg0.setPaiement(Boolean.valueOf(true));
      final int _reserverSpectacle__return = port.reserverSpectacle(_reserverSpectacle_arg0);
      System.out.println("reserverSpectacle.result=" + _reserverSpectacle__return);


    }
    {
      System.out.println("Invoking recupererReservation...");
      final int _recupererReservation_arg0 = -974377598;
      final java.util.List<javaee.spectacle.webservices.Reservation> _recupererReservation__return =
          port.recupererReservation(_recupererReservation_arg0);
      System.out.println("recupererReservation.result=" + _recupererReservation__return);


    }
    {
      System.out.println("Invoking payerSpectacle...");
      final int _payerSpectacle_arg0 = 482263062;
      final boolean _payerSpectacle__return = port.payerSpectacle(_payerSpectacle_arg0);
      System.out.println("payerSpectacle.result=" + _payerSpectacle__return);


    }
    {
      System.out.println("Invoking annulerSpectacle...");
      final int _annulerSpectacle_arg0 = -1023414804;
      final boolean _annulerSpectacle__return = port.annulerSpectacle(_annulerSpectacle_arg0);
      System.out.println("annulerSpectacle.result=" + _annulerSpectacle__return);


    }
    {
      System.out.println("Invoking trouverSpectacle...");
      final javaee.spectacle.webservices.Spectacle _trouverSpectacle_arg0 =
          new javaee.spectacle.webservices.Spectacle();
      _trouverSpectacle_arg0.setDate(Long.valueOf(-611031019760575881l));
      _trouverSpectacle_arg0.setId(Integer.valueOf(-66491050));
      _trouverSpectacle_arg0.setPrix(Integer.valueOf(1142482742));
      _trouverSpectacle_arg0.setTitre("Titre741806974");
      _trouverSpectacle_arg0.setType("Type2025432771");
      _trouverSpectacle_arg0.setVille("Ville-1969743417");
      final java.util.List<javaee.spectacle.webservices.Spectacle> _trouverSpectacle__return =
          port.trouverSpectacle(_trouverSpectacle_arg0);
      System.out.println("trouverSpectacle.result=" + _trouverSpectacle__return);


    }

    System.exit(0);
  }

}
